eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    url: mysql-db-instance.cl4wekm08mox.us-east-1.rds.amazonaws.com:3306/restaurantdb
    password: password13
    username: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
