server:
  port: 9093

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/userdb
    password: password
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
