server:
  port: 9094

spring:
  application:
    name: ORDER-SERVICE
  data:
    mongodb:
      uri: mongodb://USERNAME:PASSWORD@localhost:27017/orderdb
      database: orderdb
      repositories:
        enabled: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
